import type { Metadata } from "next";
import "./globals.css";

import { Quicksand } from "next/font/google";
import { Footer } from "@/components/Footer";
import Header from "@/components/Header";

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
  weight: ["500", "700"],
});

export const metadata: Metadata = {
  title: "Mónika Családállítás",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="hu" className={`${quicksand.variable} antialiased`}>
      <body className="font-main antialiased text-foreground">
        <div className="min-h-screen flex flex-col">
          <Header />

          <main className="flex-1">
            <div className="container mx-auto py-8">
              {children}
            </div>
          </main>

          <Footer />
        </div>
      </body>
    </html>
  );
}
